FROM supabase/postgres:15.8.1.038

# Define build arguments
ARG DATABASE_URL
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG ENABLE_STORAGE
ARG ENABLE_REALTIME

# Set Environment Variables
ENV DATABASE_URL=${DATABASE_URL}
ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
ENV SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENV ENABLE_STORAGE=${ENABLE_STORAGE}
ENV ENABLE_REALTIME=${ENABLE_REALTIME}

CMD ["sh", "-c", "supabase start"]